// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNFD6jVIcx0AFcEGQIvClQFBENNF8xExc',
    appId: '1:622371209605:web:9cf536c52984a7db3a44ec',
    messagingSenderId: '622371209605',
    projectId: 'learn-firebase-51422',
    authDomain: 'learn-firebase-51422.firebaseapp.com',
    databaseURL: 'https://learn-firebase-51422-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learn-firebase-51422.appspot.com',
    measurementId: 'G-EHS6JETL67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKtXvELpuW5TqnvvAR9LZXk1dUpJW2Omc',
    appId: '1:622371209605:android:1d03c3796a61646e3a44ec',
    messagingSenderId: '622371209605',
    projectId: 'learn-firebase-51422',
    databaseURL: 'https://learn-firebase-51422-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learn-firebase-51422.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3bsX-phSlCkRP8bWslfNj7mJin0iDgF4',
    appId: '1:622371209605:ios:4e39ed5c2286adf83a44ec',
    messagingSenderId: '622371209605',
    projectId: 'learn-firebase-51422',
    databaseURL: 'https://learn-firebase-51422-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learn-firebase-51422.appspot.com',
    androidClientId: '622371209605-8e2ofq7616togjcrp8igpu1nhudcsqg6.apps.googleusercontent.com',
    iosClientId: '622371209605-brc64vaho39fejsbbns2hq76gut574m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );

}